name: publish-release

on:
  push:
    branches: [ feature/PPCO-2470 ]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install-jq
        run: sudo apt update && sudo apt install jq -y

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr

                
      - name: Get tag version
        id: vars
        run: echo "tag_version=$(cat composer.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Create tag version and push current repo code
        run: |
          git tag v${{ steps.vars.outputs.tag_version }} master
          git push origin v${{ steps.vars.outputs.tag_version }}
          
      - name: publish-tag-release
        env:
          SSH_SDK_DEPLOY_KEY_TEST: ${{ secrets.SSH_SDK_DEPLOY_KEY_TEST }}
          GIT_USER_NAME: 'marcelonader-meli'
          GIT_USER_EMAIL: 'marcelo.nader@mercadolivre.com'
          DESTINATION_REPOSITORY_USERNAME: 'mnader_meli'
          DESTINATION_REPOSITORY_NAME: 'fury_pp-php-sdk'
          TAG_VERSION: cat composer.json | jq -r '.version'
        run: bin/publish-tag-release.sh
